releng:
  host: http://mockserver:1080

management:
  endpoints:
    web:
      exposure:
        include: health, env, metrics, threaddump, heapdump, info, configprops, prometheus, loggers

logging:
  level:
    org.octopusden.octopus.releasemanagement.controller: trace
