releng:
  url: http://mockserver:1080

jira1:
  host: http://mockserver:1080
  username: admin
  password: admin

components-registry-service:
  url: http://components-registry-service:4567

management:
  endpoints:
    web:
      exposure:
        include: health, env, metrics, threaddump, heapdump, info, configprops, prometheus, loggers

logging:
  level:
    org.octopusden.octopus.releasemanagement.controller: trace
