version: '3'

services:
  release-management-service:
    container_name: release-management-service-ft-release-management-service
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/release-management-service:${RELEASE_MANAGEMENT_SERVICE_VERSION}
    ports:
      - "8080:8080"
    volumes:
      - ./application-ft.yml:/application-ft.yml
      - ./bootstrap-ft.yml:/bootstrap-ft.yml
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - SPRING_PROFILES_ACTIVE=ft

  mockserver:
    container_name: release-management-service-ft-mockserver
    image: ${DOCKER_REGISTRY}/mockserver/mockserver:mockserver-${MOCKSERVER_VERSION}
    ports:
      - "1080:1080"

  components-registry-service:
    container_name: release-management-service-ft-components-registry-service
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/components-registry-service:${OCTOPUS_COMPONENTS_REGISTRY_SERVICE_VERSION}
    ports:
      - "4567:4567"
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - SPRING_PROFILES_ACTIVE=ft
      - SPRING_CLOUD_CONFIG_ENABLED=false
    volumes:
      - ./components-registry-service.yaml:/application-ft.yaml
      - ./../../test-common/src/main/components-registry:/components-registry

  teamcity:
    image: ${DOCKER_REGISTRY}/jetbrains/teamcity-server:${TEAMCITY_VERSION}
    container_name: release-management-service-ft-teamcity
    ports:
      - "8111:8111"
    volumes:
      - ./../build/teamcity-server/datadir:/data/teamcity_server/datadir
      - ./../build/teamcity-server/logs:/opt/teamcity/logs
    healthcheck:
      test: curl -u admin:admin -f teamcity:8111/app/rest/server >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  teamcity-agent:
    image: ${DOCKER_REGISTRY}/jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    container_name: release-management-service-ft-teamcity-agent
    privileged: true
    volumes:
      - ./buildAgent.properties:/data/teamcity_agent/conf/buildAgent.properties
