name: Common Java Gradle Build

on:
  workflow_call:
    inputs:
      flow-type:
        required: true
        type: string
      java-version:
        required: true
        type: string
      docker-image:
        required: false
        type: string
        default: ""
      skip-tests:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKIP_TESTS: ""
      BUILD_VERSION: 1.0-SNAPSHOT

    steps:
      - name: Public flow
        if: inputs.flow-type == 'public'
        run: |
          echo "Public flow, run with tests"

      - name: Hybrid flow
        if: inputs.flow-type == 'hybrid' && inputs.skip-tests
        run: |
          echo "Hybrid flow, skip tests"
          echo "SKIP_TESTS=-x test -x koverVerify -x koverCachedVerify -x koverXmlReport -x koverHtmlReport -x koverMergedVerify -x koverMergedXmlReport -x koverMergedHtmlReport" >> "$GITHUB_ENV"

      - name: Unknown flow
        if: inputs.flow-type != 'public' && inputs.flow-type != 'hybrid'
        run: |
          echo "Unknown flow specified, should be one of {public, hybrid}: ${{ inputs.flow-type }}"
          exit 1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: temurin
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Gradle build
        if: inputs.docker-image == ''
        run: ./gradlew build ${{ env.SKIP_TESTS }} -PbuildVersion=${{ env.BUILD_VERSION }} -Pversion=${{ env.BUILD_VERSION }} --info -s

      - name: Gradle build docker image
        if: inputs.docker-image != ''
        run: ./gradlew build dockerBuildImage ${{ env.SKIP_TESTS }} -Poctopus.github.docker.registry=ghcr.io -Pdocker.registry=docker.io -PbuildVersion=${{ env.BUILD_VERSION }} -Pversion=${{ env.BUILD_VERSION }} --info -s
